################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,1920x1080@60,auto,1

#################
### AUTOSTART ###
#################

exec-once = waybar &
exec-once = swaync -c ~/.config/swaync/config.json -s ~/.config/swaync/style.css &
exec-once = ~/.config/hypr/scripts/swallpaper.sh /home/bingus/Downloads/wallpaper.jpeg
exec-once = sleep 1 && nm-applet --indicator
exec-once = ~/.config/hypr/scripts/battery-alert.sh &
exec-once = ~/.config/hypr/scripts/usb-alert.sh &
exec-once = paplay /home/bingus/.config/hypr/sounds/startup.wav

# Layer Rules for Waybar and SwayNC
layerrule = blur waybar
layerrule = blur swaync-control-center
layerrule = blur swaync-notification-window

# exec-once = hyprpanel-client
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'BigBlueTermPlus Nerd Font Mono Bold 18'

exec-once = /usr/lib/hyprpolkitagent 
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hypridle
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# exec-once = flatpak run com.spotify.Client

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.cache/wal/colors-hyprland.conf

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

ecosystem {
    no_update_news = true
}

env = QT_QPA_PLATFORMTHEME,qt5ct
env = GNOME_SCHEMA,org.gnome.desktop.interface
env = SAL_USE_VCLPLUGIN,gtk3

###################
### PERMISSIONS ###
###################


#####################
### LOOK AND FEEL ###
#####################

source = /home/bingus/.config/hypr/configs/animations.conf

#############
### INPUT ###
#############

source = /home/bingus/.config/hypr/configs/input.conf

###################
### KEYBINDINGS ###
###################

source = /home/bingus/.config/hypr/configs/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev = float,class:^$,title:^$,xwayland:1

# Force Spotify to Workspace 10 and keep it silent (don't switch focus to it)
windowrulev = workspace 10 silent, class:^(com.spotify.Client)$

exec-once = powerprofilesctl set power-saver
exec-once = udiskie &

# misc {
#     vfr = true
# }
