[FileDialog]
history=file:///home/bingus, file:///home/bingus/Downloads, file:///home/bingus/pt/saves, file:///home/bingus/Downloads/Zen-Download/qbittorrent/webui, file:///opt/qbittorrent, file:///opt/qbittorrent/webui
lastVisited=file:///opt/qbittorrent/webui
qtVersion=6.10.1
shortcuts=file:, file:///home/bingus
sidebarWidth=93
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb0\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xde\0\0\0\x1\0\0\0\0\0\0\0\x36\0\0\0\x1\0\0\0\0\0\0\0:\0\0\0\x1\0\0\0\0\0\0\0\x62\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
