#----------------------------------------------------------------------------------------------------->
#
#    ooooo                                        .   
#    `888'                                      .o8   
#     888  ooo. .oo.   oo.ooooo.  oooo  oooo  .o888oo 
#     888  `888P"Y88b   888' `88b `888  `888    888   
#     888   888   888   888   888  888   888    888   
#     888   888   888   888   888  888   888    888 . 
#    o888o o888o o888o  888bod8P'  `V88V"V8P'   "888" 
#                       888                           
#                      o888o                                                                               
#
#----------------------------------------------------------------------------------------------------->
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

#
#----------------------------------------------------------------------------------------------------->
#
#
#----------------------------------------------------------------------------------------------------->
#
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
#
#----------------------------------------------------------------------------------------------------->
