#----------------------------------------------------------------------------------------------------->
#
#    ooooo                                        .   
#    `888'                                      .o8   
#     888  ooo. .oo.   oo.ooooo.  oooo  oooo  .o888oo 
#     888  `888P"Y88b   888' `88b `888  `888    888   
#     888   888   888   888   888  888   888    888   
#     888   888   888   888   888  888   888    888 . 
#    o888o o888o o888o  888bod8P'  `V88V"V8P'   "888" 
#                       888                           
#                      o888o                                                                               
#
#----------------------------------------------------------------------------------------------------->
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
    }
}

# gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
#     workspace_swipe_distance = 300
#     workspace_swipe_invert = true
#     workspace_swipe_min_speed_to_force = 30
#     workspace_swipe_cancel_ratio = 0.5
# }

#
#----------------------------------------------------------------------------------------------------->
#
#
#----------------------------------------------------------------------------------------------------->
#
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
#
#----------------------------------------------------------------------------------------------------->
